#!/bin/bash

source /usr/share/yunohost/helpers

timezone="$(cat /etc/timezone)"
ynh_app_setting_set --key=timezone --value="$timezone"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#TODO: Check if this can be removed
chown -R $app:www-data "$install_dir"
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding app's configuration file..."

ynh_config_add --template="config.inc.php" --destination="$install_dir/web/config.inc.php"
#TODO: Check if this can be removed
chmod 600 "$install_dir/web/config.inc.php"
chown "$app:$app" "$install_dir/web/config.inc.php"

ynh_config_add --template="config-ynh.inc.php" --destination="$install_dir/web/config-ynh.inc.php"
chmod 400 "$install_dir/web/config-ynh.inc.php"
chown "$app:$app" "$install_dir/web/config-ynh.inc.php"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
  # some_command --build
popd

#=================================================
# CREATE DB TABLES
#=================================================
ynh_script_progression "Initializing database..."

PGPASSWORD="$db_pwd" psql -h localhost -f $install_dir/tables.pg.sql $db_name $db_user

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
