#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="web/config.inc.php web/config-ynh.inc.php"

#TODO: Check if this can be removed
chown -R $app:www-data "$install_dir"
#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# UPDATE APP CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading app configurations for $app..."

# Upgrade/overwrite config-ynh.inc.php
ynh_backup_if_checksum_is_different "$install_dir/web/config-ynh.inc.php"
ynh_config_add --template="config-ynh.inc.php" --destination="$install_dir/web/config-ynh.inc.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
